server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;

	# Make site accessible from http://localhost/
	server_name localhost;

	# Set project index
	index index.php index.html;

	# Set project path
	root /var/www/site/public;

	# Set the character set to utf8
	charset utf-8;

	# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
	#
	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ /index.php?$query_string;
	}

	# Set expires header for all static files
	#
	location ~* \.(jpg|jpeg|gif|png|css|js|ico|xml)$ {
		expires 	30d;
	}

	error_page 404 /index.php;

	sendfile off;

	# redirect server error pages to the static page /50x.html
	#
	#error_page 500 502 503 504 /50x.html;
	#location = /50x.html {
	#	root /usr/share/nginx/html;
	#}

	# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
	#
	location ~ .php$ {
		# connect to a unit domain-socket:
        fastcgi_pass    unix:/run/php/php7.1-fpm.sock;
		fastcgi_index 	index.php;

		fastcgi_param 	SCRIPT_FILENAME 	$document_root$fastcgi_script_name;
		fastcgi_param 	SCRIPT_NAME	        $fastcgi_script_name;

		fastcgi_buffer_size 128k;
		fastcgi_buffers 256 16k;
		fastcgi_busy_buffers_size 256k;
		fastcgi_temp_file_write_size 256k;

		# This file is present
		include fastcgi_params;
	}

	# deny access to .htaccess files, if Apache's document root
	# concurs with nginx's one
	#
	location ~ /\.ht {
		deny all;
	}
}
