name: CI

on:
  push:
    branches: [ 'master', '*.x' ]
  pull_request:
    branches: [ 'master', '*.x' ]

permissions:
  pull-requests: write
  contents: read

jobs:
  commit-message-check:
    name: Commit Message Check
    if: github.event_name == 'pull_request'
    uses: valkyrjaio/.github/.github/workflows/_commit-message-check.yml@d717ed56a6228d6dbd99a854d03d8a92fc43ad3f
    secrets: inherit

  trailing-newline-check:
    name: Trailing Newline Check
    if: github.event_name == 'pull_request'
    uses: valkyrjaio/.github/.github/workflows/_trailing-newline-check.yml@d717ed56a6228d6dbd99a854d03d8a92fc43ad3f
    permissions:
      pull-requests: write
      contents: read
    secrets: inherit
