name: Create Yearly Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming yearly release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_create-version-branch.yml@1438ce03055b4ad8010e8dfd863aa85d07f122ad
    secrets: inherit
