name: Create Yearly Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming yearly release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_create-version-branch.yml@699060a99b1eb0c346bc66dc33e99410f5de55d7
    secrets: inherit
