name: Create Major Release Version Branch

on: workflow_dispatch

run-name: Create new version for upcoming major release

jobs:
  create:
    uses: valkyrjaio/.github/.github/workflows/_create-version-branch.yml@a05d561b0818440bcd533380e5adf994d5f5e8d5
    secrets: inherit
